version: "3"
services:

  api:
    build:
      context: ../src/api
    networks:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - ../src/api/server:/tmp/api/server
    env_file: .env
    environment:
      - PYTHONPATH=/tmp/api/
    command: bash -c "cd /tmp/api/server && gunicorn app:app --bind 0.0.0.0:8000  --reload --worker-class sanic.worker.GunicornWorker"

networks:
  backend:
